"""
CloudShield Enterprise
Enterprise CSV Report Export
"""

import csv
import json


class CSVReport:

    @staticmethod
    def _write_section(writer, title):
        writer.writerow([])
        writer.writerow([title])
        writer.writerow(["Property", "Value"])

    @staticmethod
    def _write_dict(writer, data):
        if not isinstance(data, dict):
            writer.writerow(["Value", str(data)])
            return

        for key, value in data.items():
            if isinstance(value, (dict, list)):
                value = json.dumps(value, indent=2)
            writer.writerow([key.replace("_", " ").title(), value])

    def generate(self, scan, filename):

        try:
            parsed = json.loads(scan.parsed_output or "{}")
        except Exception:
            parsed = {}

        with open(filename, "w", newline="", encoding="utf-8") as file:

            writer = csv.writer(file)

            # ==================================================
            # TITLE
            # ==================================================

            writer.writerow(["CloudShield Enterprise"])
            writer.writerow(["Security Assessment Report"])
            writer.writerow([])

            # ==================================================
            # EXECUTIVE SUMMARY
            # ==================================================

            self._write_section(writer, "Executive Summary")

            writer.writerow(["Target", scan.target])
            writer.writerow(["Category", scan.category])
            writer.writerow(["Tool", scan.tool])
            writer.writerow(["Status", scan.status])
            writer.writerow(["Risk", scan.risk])
            writer.writerow(["Security Score", f"{scan.score}%"])
            writer.writerow(["Started", scan.started_at])
            writer.writerow(["Completed", scan.completed_at])

            # ==================================================
            # PARSED DATA
            # ==================================================

            skip = {"html", "body", "cookies", "response", "raw_html"}

            for key, value in parsed.items():

                if key.lower() in skip:
                    continue

                self._write_section(writer, key.replace("_", " ").title())

                if isinstance(value, dict):

                    self._write_dict(writer, value)

                elif isinstance(value, list):

                    if len(value) == 0:
                        writer.writerow(["Value", "No Results"])

                    else:

                        for item in value:

                            if isinstance(item, dict):
                                writer.writerow([])
                                self._write_dict(writer, item)
                            else:
                                writer.writerow(["Value", item])

                else:

                    writer.writerow(["Value", value])

            # ==================================================
            # FOOTER
            # ==================================================

            writer.writerow([])
            writer.writerow(["Generated By", "CloudShield Enterprise"])
            writer.writerow(
                [
                    "Disclaimer",
                    "For educational and authorized security assessments only.",
                ]
            )

        return filename
