"""
CloudShield Enterprise
Enterprise CSV Report Export
"""

import csv
import json


class CSVReport:

    @staticmethod
    def _write_section(writer, title):
        writer.writerow([])
        writer.writerow([title])
        writer.writerow(["Property", "Value"])

    @staticmethod
    def _write_dict(writer, data):
        if not isinstance(data, dict):
            writer.writerow(["Value", str(data)])
            return

        for key, value in data.items():
            if isinstance(value, (dict, list)):
                value = json.dumps(value, indent=2)
            writer.writerow([key.replace("_", " ").title(), value])

    def generate(self, scan, filename):

        try:
            parsed = json.loads(scan.parsed_output or "{}")
        except Exception:
            parsed = {}

<<<<<<< HEAD
        with open(filename, "w", newline="", encoding="utf-8") as file:
=======
        with open(
            filename,
            "w",
            newline="",
            encoding="utf-8"
        ) as file:
>>>>>>> ced70e1725c55fe0379baaf4f6a4ee392ae289d5

            writer = csv.writer(file)

            # ==================================================
            # TITLE
            # ==================================================

            writer.writerow(["CloudShield Enterprise"])
            writer.writerow(["Security Assessment Report"])
            writer.writerow([])

            # ==================================================
            # EXECUTIVE SUMMARY
            # ==================================================

            self._write_section(writer, "Executive Summary")

            writer.writerow(["Target", scan.target])
            writer.writerow(["Category", scan.category])
            writer.writerow(["Tool", scan.tool])
            writer.writerow(["Status", scan.status])
            writer.writerow(["Risk", scan.risk])
            writer.writerow(["Security Score", f"{scan.score}%"])
            writer.writerow(["Started", scan.started_at])
            writer.writerow(["Completed", scan.completed_at])

            # ==================================================
            # PARSED DATA
            # ==================================================

<<<<<<< HEAD
            skip = {"html", "body", "cookies", "response", "raw_html"}
=======
            skip = {
                "html",
                "body",
                "cookies",
                "response",
                "raw_html"
            }
>>>>>>> ced70e1725c55fe0379baaf4f6a4ee392ae289d5

            for key, value in parsed.items():

                if key.lower() in skip:
                    continue

<<<<<<< HEAD
                self._write_section(writer, key.replace("_", " ").title())
=======
                self._write_section(
                    writer,
                    key.replace("_", " ").title()
                )
>>>>>>> ced70e1725c55fe0379baaf4f6a4ee392ae289d5

                if isinstance(value, dict):

                    self._write_dict(writer, value)

                elif isinstance(value, list):

                    if len(value) == 0:
                        writer.writerow(["Value", "No Results"])

                    else:

                        for item in value:

                            if isinstance(item, dict):
                                writer.writerow([])
                                self._write_dict(writer, item)
                            else:
                                writer.writerow(["Value", item])

                else:

<<<<<<< HEAD
                    writer.writerow(["Value", value])
=======
                    writer.writerow(
                        [
                            "Value",
                            value
                        ]
                    )
>>>>>>> ced70e1725c55fe0379baaf4f6a4ee392ae289d5

            # ==================================================
            # FOOTER
            # ==================================================

            writer.writerow([])
            writer.writerow(["Generated By", "CloudShield Enterprise"])
            writer.writerow(
                [
                    "Disclaimer",
<<<<<<< HEAD
                    "For educational and authorized security assessments only.",
                ]
            )

        return filename
=======
                    "For educational and authorized security assessments only."
                ]
            )

        return filename
>>>>>>> ced70e1725c55fe0379baaf4f6a4ee392ae289d5
