"""Add finding enterprise fields

Revision ID: 2a1b1271bff7
Revises: 855cc2660e1d
Create Date: 2026-07-20 12:54:03.678960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a1b1271bff7'
down_revision = '855cc2660e1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('mitre', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('vulnerability_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('remediation', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('impact', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('affected_component', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('verified_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_column('verified_at')
        batch_op.drop_column('verified_by')
        batch_op.drop_column('verified')
        batch_op.drop_column('affected_component')
        batch_op.drop_column('impact')
        batch_op.drop_column('remediation')
        batch_op.drop_column('vulnerability_type')
        batch_op.drop_column('mitre')
        batch_op.drop_column('reference')

    # ### end Alembic commands ###
